apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: lakshminarayanam/jenkins_auto_app:latest
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000 
    targetPort: 8000
    nodePort: 31110
